get some useful data via ceph daemon admin socket
SUSE/supportutils-plugin-ses pull request #9
Opened 2018-07-04 10:09 UTC by trociny

Signed-off-by: Mykola Golub <mgolub@suse.com>

2018-07-06 12:25 UTC, tserong requested changes

2018-07-06 12:25 UTC, tserong commented on ses
> +    ps auxww | sed -nEe 's/^.*ceph-(mds|mgr|mon|osd) .*-i *([^ ]*) .*/\1.\2/p' |
The systemd unit files use the long form `--id` argument when starting daemons, which doesn't work with the above sed invocation (it comes back with `mon.d`, instead of `mon.$HOSTNAME`).

`sed -nEe 's/^.*ceph-(mds|mgr|mon|osd) .*-id? *([^ ]*) .*/\1.\2/p'` seems to work with both short `-i` and long `--id` form arguments.

2018-07-06 12:25 UTC, tserong commented on ses
> +                ceph --connect-timeout=$CT daemon ${daemon} dump_historic_ops \
`dump_historic_ops` gives "admin_socket: invalid command" on luminous MONs (although it's probably safe to keep this, as it will work in mimic, and if run on luminous should just result in the invalid command error being dumped to the log file, which is basically harmless).

2018-07-06 18:44 UTC, trociny commented on ses
> +    ps auxww | sed -nEe 's/^.*ceph-(mds|mgr|mon|osd) .*-i *([^ ]*) .*/\1.\2/p' |
@tserong thanks! updated.

2018-07-06 18:48 UTC, trociny commented on ses
> +                ceph --connect-timeout=$CT daemon ${daemon} dump_historic_ops \
My vote is for keeping this.

2018-07-09 06:17 UTC, tserong commented on ses
> +                ceph --connect-timeout=$CT daemon ${daemon} dump_historic_ops \
Cool

2018-07-09 06:18 UTC, tserong approved these changes

2018-07-09 06:18 UTC, merged